spring.application.name=xisum

spring.datasource.url=jdbc:postgresql://localhost:${XISUM_DB_PORT}/${XISUM_DB}
spring.datasource.username=${XISUM_DB_USER}
spring.datasource.password=${XISUM_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT}

app.admin.import-key=${ADMIN_IMPORT_KEY}

room.base.link=http://localhost:8080/
